# Generated by Django 3.0.8 on 2020-07-22 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20200722_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('city', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
