# Generated by Django 3.0.8 on 2020-07-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200721_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Jeans', 'Jeans'), ('Sport Wear', 'Sport Wear'), ('Outwear', 'Outwear')], max_length=20),
        ),
    ]
