# Generated by Django 3.0.8 on 2020-07-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
