# Generated by Django 3.0.8 on 2020-07-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200722_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('J', 'Jeans'), ('SW', 'Sport Wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
