# Generated by Django 3.0.8 on 2020-07-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200725_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
